### PR TITLE
(QA-2634) rototiller command add_argument

### PR DESCRIPTION
**Pull request by er0ck**
(QA-2634) command add_argument docs

* also fixup add_option docs

(QA-2634) update class diagram and Rakefile docs:class_graph

(QA-2634) rototiller command add_argument acceptance tests

(QA-2634) rototiller command: add_argument spec tests

(QA-2634) fixup some comments and spurious code in command Option

(QA-2634) rototiller command: add_argument

(maint) fix dog-fooding issue in our Rakefile  …

* previously we were loading all of rototiller into the LOAD_PATH in the
gemspec file just so we could enable unit testing. This causes issues
when using the Rakefile, which loads the same code when using a
breakpoint anywhere in the code or tests. The debugger would never
yield to the prompt.
  * this also means we have to remove the call to the gemspec in the
    Gemfile. bundler doesn't allow the inclusion of the same gem twice.
* we can't have changes to our code breaking our own rakefile, so we
* need to dogfood the stable version of rototiller.
* we also remove the spec files from the gem, and add in missing files

### CODE REVIEW

**Comment by er0ck** [comment]
@zreichert it's a start.  needs docs

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by er0ck** [comment]
retest this please

**Comment by zreichert** [comment]
👍

**Pull request merged**
