### PR TITLE
(maint) fix osx gem install

### PR DESCRIPTION
**Pull request by er0ck**
also:
* (maint) update qa email address in gemspec

this should fix osx installs for acceptance

### CODE REVIEW

**Comment by er0ck** [comment]
@zreichert this should fix ubuntu1604 also.  pls merge when acceptance job finishes...
rebase your changes,
then go try `test this please` in your PR

**Comment by er0ck** [comment]
@zreichert ugh... okay, this should work now.  what a PITA

**Comment by zreichert** [comment]
test this please

**Comment by zreichert** [comment]
@puppetlabs-jenkins retest this please

**Comment by zreichert** [comment]
@er0ck This still fails on OSX 10.11, I am inclined to remove this from the matrix.  This has failed trying to find bundler.  Same ruby version as 10.10

**Comment by zreichert** [comment]
@er0ck Once https://github.com/puppetlabs/ci-job-configs/pull/1967 is merged I'll merge this PR

**Comment by zreichert** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
